name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks:
    name: Run Gitleaks Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu Checkout Et
        uses: actions/checkout@v4

      - name: Gitleaks ile Secret Taraması
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-banner --redact

  build-and-test:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Repo'yu Checkout Et
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bağımlılıkları Yükle
        run: npm install

      - name: Testleri Çalıştır
        run: npm test
